sample_app/config/routes.rb
Rails.application.routes.draw do
  resources :users do
     member do
       get :following, :followers
     end
   end
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  match '/signup',  to: 'users#new',            via: 'get'
    match '/signin',  to: 'sessions#new',         via: 'get'
    match '/signout', to: 'sessions#destroy',     via: 'delete'
    root "static_pages#index"
    match '/help',   to: 'static_pages#help',   via: 'get'
    match '/about',   to: 'static_pages#about',   via: 'get'
    get "static_pages/contact"

end

sample_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", static_pages_contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

sample_app/app/views/layouts/_header.html.erb
<header> 
	<nav class="navbar navbar-inverse navbar-fixed-top"> 
		<div class="navbar-inner"> <div class="container"> 
			<%= link_to "sample app", '#', id: "logo" %> 
			<nav> 
				<ul class="nav nav-pills pull-right"> 
					<li><%= link_to "Home", root_path %></li> 
					<li><%= link_to "Help", help_path %></li> 
					
					<% if signed_in? %> 
					<li><%= link_to "Users", users_path %></li> 
					<li id="fat-menu" class="dropdown">
						 <a href="#" class="dropdown-toggle" data-toggle="dropdown"> Account
							  <b class="caret"></b> 
						  </a>
						  <ul class="dropdown-menu"> 
							  <% #but Rails allows us to link directly to the user, in this context automatically converting
							  # current_user into user_path(current_user).
							  %>
							  <li><%= link_to "Profile", current_user %></li> 
							  <li><%= link_to "Settings", edit_user_path(current_user) %></li> <li class="divider"></li>
							   <li> <%= link_to "Sign out", signout_path, method: "delete" %> </li>
						   </ul> 
					   </li> 
					   <% else %> 
					   <li><%= link_to "Sign in", signin_path %></li> 
					   <% end %> 
				    </ul>  
				</nav> 
			</div>
		</div>
	</nav> 
</header>
	

	  
	   

sample_app/app/views/layouts/_shim.html.erb
  <!--it’s actually a conditional comment supported by Internet Explorer browsers for just this sort of situation-->
  <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
      <![endif]-->

sample_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> <%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
     <%= render 'layouts/shim' %>
</head>
<body>

    <%= render 'layouts/header' %>
    <div class="container">
	 <% flash.each do |key, value| %>
	         <div class="alert alert-<%=  flash_class(key) %>"><%= value %></div>
	       <% end %>
	 
	  <%= yield %>
	
	  <%= render 'layouts/footer' %>
	   <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>